version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmdtgbot
    environment:
      - TELEGRAM_BOT_TOKEN = "7753926190:AAGiIpvrOGTG7_SSPkPHHm3xMGuypqc44NU"
      - REMOTE_SERVER_USER = "root"
      - VIDEO_PUSH_SERVER_IP_A = "10.141.11.201"
      - VIDEO_PUSH_SERVER_IP_B = "10.141.11.202"
      - VIDEO_FILE_SERVER_IP = "10.141.11.201"
      - VIDEO_PUSH_SERVER_IP_PASSWORD = "BTvide0>>>"
      - AUTHORIZED_USER_IDS = "1028254059,5529798900"
    restart: unless-stopped
    # Optional: If you need to mount any volumes for persistent data (e.g., logs)
    # volumes:
    #   - ./logs:/app/logs
