version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmdtgbot
    environment:
      # Telegram Bot Token - REPLACE WITH YOUR ACTUAL TOKEN OR USE AN ENV FILE
      - TELEGRAM_BOT_TOKEN=
      # Remote Server User
      - REMOTE_SERVER_USER=
      # Video Push Server IP A
      - VIDEO_PUSH_SERVER_IP_A=
      # Video Push Server IP B
      - VIDEO_PUSH_SERVER_IP_B=
      # Video File Server IP (currently not used in bot logic)
      - VIDEO_FILE_SERVER_IP=
      # Password for remote server SSH connection (BE CAREFUL WITH HARDCODING PASSWORDS)
      - VIDEO_PUSH_SERVER_IP_PASSWORD=
      # Comma-separated list of authorized Telegram User IDs
      - AUTHORIZED_USER_IDS=
    restart: unless-stopped
    # Optional: If you need to mount any volumes for persistent data (e.g., logs)
    # volumes:
    #   - ./logs:/app/logs
