version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmdtgbot
    environment:
      # Telegram Bot Token - REPLACE WITH YOUR ACTUAL TOKEN OR USE AN ENV FILE
      - TELEGRAM_BOT_TOKEN=7753926190:AAGiIpvrOGTG7_SSPkPHHm3xMGuypqc44NU
      # Remote Server User
      - REMOTE_SERVER_USER=root
      # Video Push Server IP A
      - VIDEO_PUSH_SERVER_IP_A=10.141.11.201
      # Video Push Server IP B
      - VIDEO_PUSH_SERVER_IP_B=10.141.11.202
      # Video File Server IP (currently not used in bot logic)
      - VIDEO_FILE_SERVER_IP=10.141.11.201
      # Password for remote server SSH connection (BE CAREFUL WITH HARDCODING PASSWORDS)
      - VIDEO_PUSH_SERVER_IP_PASSWORD=BTvide0>>>
      # Comma-separated list of authorized Telegram User IDs
      - AUTHORIZED_USER_IDS=1028254059,5529798900
    restart: unless-stopped
    # Optional: If you need to mount any volumes for persistent data (e.g., logs)
    # volumes:
    #   - ./logs:/app/logs