version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmdtgbot
    environment:
      - TELEGRAM_BOT_TOKEN = 
      - REMOTE_SERVER_USER = 
      - VIDEO_PUSH_SERVER_IP_A = 
      - VIDEO_PUSH_SERVER_IP_B = 
      - VIDEO_FILE_SERVER_IP = 
      - VIDEO_PUSH_SERVER_IP_PASSWORD = 
      - AUTHORIZED_USER_IDS = 
    restart: unless-stopped
    # Optional: If you need to mount any volumes for persistent data (e.g., logs)
    # volumes:
    #   - ./logs:/app/logs
